Read/write timeseries section of inp
aerispaha/swmmio pull request #113
Opened 2020-12-03 19:56 UTC by jackieff

#57 Addresses TIMESERIES section. Model object can now read timeseries section (direct data and file-pointers). `replace_inp_section` also works. Added a file-pointing timeseries into `model_full_features_network.inp` for testing.

2020-12-03 22:22 UTC, aerispaha requested changes
This rules, thanks @jackieff! 

My only request is that we add an actual assertion in the `test_get_set_timeseries` unit test

2020-12-03 22:22 UTC, aerispaha commented on swmmio/core.py
> +        self._polygons_df = df
Oh wow is this a bonus bug fix?

2020-12-03 22:22 UTC, aerispaha commented on swmmio/tests/test_model_elements.py
> +    ts = test_model_01.inp.timeseries
Can we assert something here?

2020-12-04 01:20 UTC, jackieff commented on swmmio/core.py
> +        self._polygons_df = df
Think so!

2020-12-04 04:07 UTC, jackieff commented on swmmio/tests/test_model_elements.py
> +    ts = test_model_01.inp.timeseries
Done!

2020-12-04 14:25 UTC, aerispaha approved these changes
Cool!

2020-12-04 14:27 UTC, merged