write_inp_section changes - don't change the Polygons header
aerispaha/swmmio pull request #182
Opened 2023-01-19 12:13 UTC by BuczynskiRafal

2023-01-19 12:17 UTC, BuczynskiRafal commented
@aerispaha I'm not sure how to test the solution. Can I find a method in swmmio that reads the header in the inp file to compare it with the header after doing replace_inp_section?

2023-01-22 14:00 UTC, bemcdonnell commented
@BuczynskiRafal, I'm guessing you're adding this feature because of some kind of text version control issue.   I think the best way to test it is to add a second INP file with `[POLYGONS]` and check the outputs from that. You can use a simple file parser to assert that the text found is either your `[Polygons]` or `[POLYGONS]`

2023-01-28 07:32 UTC, BuczynskiRafal commented
@aerispaha @bemcdonnell Please review my PR. Thank you.

2023-01-29 21:54 UTC, aerispaha requested changes
@BuczynskiRafal thanks for this great contribution to `swmmio`! Overall, your bug fix seems to work great. 

My only request is that we remove the new `swmmio/tests/data/example_polygons.inp` file from this PR, and use a test inp file that already exists in the repo. I'd also suggest we refactor the unit test as I described below for a couple reasons: 
1. this way test files aren't left behind if this test fails
2. I'd prefer to emphasize the `model.inp.<section> = <dataframe>` pattern for updating models, rather than using the `replace_inp_section` function directly.  

Let me know what you think!

2023-01-29 21:54 UTC, aerispaha commented on swmmio/tests/data/__init__.py
> +MODEL_POLYGONS = os.path.join(DATA_PATH, 'example_polygons.inp')
I don't think we need to add this new inp file to test that this bug fix works properly. Any existing test inp file in the repo with a Polygons section will do.

2023-01-29 21:54 UTC, aerispaha commented on swmmio/tests/data/model_full_features_network_xy.inp
> +;;   X             Y
Are these changes necessary for anything? If not, let's remove these changes from the PR

2023-01-29 21:54 UTC, aerispaha commented on swmmio/tests/test_version_control.py
> +def test_replace_inp_section_overwrite_polygons_header():
This tests that the bug fix works properly which is great! 

But I'd prefer store any test artifacts in a temporary file location, this way if the test fails, it won't leave behind files in the project directory. How do you feel about refactoring this unit test like this: 

```python
def test_replace_inp_section_overwrite_polygons_header():
    model = swmmio.Model(MODEL_A_PATH)

    with tempfile.TemporaryDirectory() as tempdir:

        # create a temporary inp file path
        inp_path = os.path.join(tempdir, f'{model.inp.name}.inp')

        # get a polygons dataframe and change it slightly
        polygons = model.inp.polygons
        model.inp.polygons = polygons.round(1)

        # save the updated model to disk
        model.inp.save(inp_path)

        # with this updated model, instantiate a new model object
        # and make changes to the Polygons once again
        model2 = swmmio.Model(inp_path)
        model2.inp.polygons = polygons.round(0)

        # save the model once more
        model2.inp.save()

        # confirm that there is only one instance of
        # the [Polygons] section in the inp file
        with open(inp_path, 'r') as file:
            data = file.read()
            assert data.count("[POLYGONS]") == 0
            assert data.count("[Polygons]") == 1
```

This test also uses an existing test inp file, this way we can omit the `swmmio/tests/data/example_polygons.inp` file from this PR.

2023-02-01 13:25 UTC, BuczynskiRafal commented
@aerispaha Thanks for the good points. I've made the changes.

2023-02-02 19:02 UTC, aerispaha approved these changes
This looks great, @BuczynskiRafal! I'll get this integrated into the next release asap

2023-02-02 19:05 UTC, merged